### ISSUE TITLE
Add New Contact method

### ISSUE THREAD

**Issue by ghoroubi** [ronaksoft/mtproto#1]
I am using mtproto , I had implemente all methods and there was no problem. but in adding contact!
I want to implement a method to import or add new contact(s).
anyone know how to do that?
@ehsannm 
@mhr9o2o 
@zerob4wl 
@sorousht 
@robzizo

**Comment by mhr9o2o** [comment]
@ehsannm seems to be the only one who can help you

**Comment by ghoroubi** [comment]
@mhr9o2o 
Salam, shoma kar nakardin in mozoo ro?

**Comment by ehsannm** [comment]
@ghoroubi this is library is at its very early stage of developing and subjects to change a lot and not reliable to be used in production at all.
But for your question, there is a method contacts.ImportContacts which is not implemented yet in this lib. But if you can implement any method and add it to library

https://tjhorner.com/tl-schema/#functions

Regards,
Ehsan N. Moosa

**Comment by ghoroubi** [comment]
@ehsannm 
Thank you so much.
I will do that, if I face with problem, can I ask you friend?

**Comment by ehsannm** [comment]
yes for sure

**Comment by ghoroubi** [comment]
:+1: Thank @ehsannm

**Comment by ghoroubi** [comment]
@ehsannm , Look at this code(not complete yet):

func (m *MTProto) ImportContact() {
	resp := make(chan TL, 1)

	var newContacts []TL_inputPhoneContact

	var temp TL_inputPhoneContact
	temp.client_id = 0
	temp.phone = "+989212049236"
	temp.last_name = ""
	temp.first_name = ""
	newContacts = append(newContacts, temp)

	m.queueSend <- packetToSend{TL_contacts_importContacts{contacts: newContacts, replace: false}, resp}

	x := <-resp
}
I dont know what to pass to Packettosend{msg,resp} as msg property.

**Comment by ehsannm** [comment]
```
// accepts :
// in can be:
// 	TL_inputPhoneContact
func (m *MTProto) Contacts_ImportContacts(in []TL) TL_contacts_importedContacts {
	resp := make(chan TL, 1)
	m.queueSend <- packetToSend{
		TL_contacts_importContacts{
			in,
		},
		resp,
	}
	x := <-resp
	switch r := x.(type) {
	case TL_contacts_importedContacts:
		return r
	default:
		log.Println("Error Handling Here")
	}
	return TL_contacts_importedContacts{}
}

```

The above code can do the import for you but in this lib we are not going to use it directly. Since in MTProto a function might return different structures (they call it predicator) and this is not very Golang friendly. So we are going to create Wrapper structures and fill those structs with the TL constructors.

For example CHAT predicator can have : 
1. chat
2. chatEmpty
3. chatForbidden
4. channel
5. channelForbidden

I hope that I could explain it good for you
@ghoroubi

**Comment by ghoroubi** [comment]
@ehsannm Hi again
Thank you so much my friend. I got it and will use the lib only for creating wrapper,
You are very good friend for me, thanks

**Comment by ghoroubi** [comment]
@ehsannm 
Hi friend.
I used your suggest, but there is a problem yet :(
I define TL_inputPhoneContact and create an array of TL_inputPhoneContact , but beacause your method gives []TL, I cant pass my array to it!
how can I implement the TL interface?
I am so sorry to disturb you and wasting your time, I need your help  friend
