### ISSUE TITLE
PHONE_MIGRATE_4 Error

### ISSUE THREAD

**Issue by tclass** [ronaksoft/mtproto#2]
I always get this error 
`RPC: mtproto.TL_rpc_error{error_code:303, error_message:"PHONE_MIGRATE_4"}``
then it stops, it seems to me, that the DC handling is implemented fine, but somehow the application doesn't connect to the new DC with the right command. Any ideas?

**Comment by ehsannm** [comment]
Dear @tclass this library was not supposed to be a complete lib but used by other services, however, I will add more debugging to the code. At the moment the only solution I have is that you can find DC number 4 in the dclist (map[int32]string) and set it NewMTProto (..., dcaddress, ..)

**Comment by ehsannm** [comment]
you can also use : 
func (m *MTProto) GetDcAddress (dcID int32) string

**Comment by agustind** [comment]
Before sending the code, you can call

await mtproto.setDefaultDc(4);

Change the parameter to the migrate number you get in the error
