### ISSUE TITLE
Messages_SendMessage always returns error 400 / INPUT_REQUEST_TOO_LONG

### ISSUE THREAD

**Issue by moorage** [ronaksoft/mtproto#5]
Whenever I call 
```
myString := "hello"
aUser := < some mtproto.TL_user >
mtproto.Messages_SendMessage(myString, mtproto.TL_inputPeerUser{User_id: aUser.Id, Access_hash: aUser.Access_hash}, 0)
```

I get the following error: `{400 INPUT_REQUEST_TOO_LONG}`.

I'm guessing that's something to do with the implementation of `func (e TL_messages_sendMessage) encode() []byte`, but I'm wondering if you have any guesses?

**Comment by moorage** [comment]
Here's a fix for it: https://github.com/ronaksoft/mtproto/pull/4/commits/89b926ec8a92728432331c315368cd4d16460f7f

**Comment by ehsannm** [comment]
Thanks for your pull request, it is merged to master.
